export default {
  linked: {
    name: "string",
    fullname: "string",
    preferredname: "string",
    phone: "string",
    phonenumber: "string",
    telephone: "string",
    telephonenumber: "string",
    home: "string",
    homenumber: "string",
    mobile: "string",
    mobilenumber: "string",
    address: "string",
    ssn: "string",
    socialsecurity: "string",
    socialsecurity_number: "string",
    passport: "string",
    passportnumber: "string",
    documentnumber: "string",
    driverslicensenumber: "string",
    driverslicense: "string",
    creditcard: "string",
    creditcardnumber: "string",
    geo: "string",
    geodata: "string"
  },
  linkable: {
    age: "string",
    race: "string",
    gender: "string",
    dateofbirth: "string",
    ip: "string",
    email: "string",
    emailaddress: "string",
    user: "string",
    username: "string",
    pass: "string",
    password: "string",
    firstname: "string",
    lastname: "string",
    streetnumber: "string"
  }
};
